package com.chari.chariapp.request.domain;

public enum AttachmentDocumentType {
    POPULATION_REGISTRY_EXTRACT,
    BIRTH_CERTIFICATE_COPY,
    PERSONAL_PHOTO,
    PROFESSION_PROOF,
    PAYMENT_RECEIPT,
    OLD_DOCUMENT,
    LOSS_OR_THEFT_REPORT,
    DATA_CORRECTION_PROOF,
    GUARDIANSHIP_CERTIFICATE,
    OTHER_SUPPORTING_DOCUMENT
}
