package com.chari.chariapp.notification.domain;

public enum NotificationType {
    PASSPORT_REQUEST_APPROVED, PASSPORT_REQUEST_REJECTED,
    NATIONAL_IDENTITY_REQUEST_APPROVED, NATIONAL_IDENTITY_REQUEST_REJECTED,
    BIRTH_CERTIFICATE_REQUEST_APPROVED, BIRTH_CERTIFICATE_REQUEST_REJECTED,
    APPOINTMENT_BOOKED, APPOINTMENT_CANCELLED, APPOINTMENT_COMPLETED,
    ADDITIONAL_DOCUMENTS_REQUESTED, ADDITIONAL_DOCUMENTS_ACCEPTED
}
